### ISSUE TITLE
Cannot find asset error after running cdk bootstrap

### ISSUE THREAD

**Issue by banavalikar** [aws-samples/ab-testing-at-edge#1]
Running cdk bootstrap gives: Cannot find asset at /home/ec2-user/environment/ab-testing-at-edge/resources/module_3_1/request

![image](https://user-images.githubusercontent.com/10076518/133420781-388c32b6-ccd6-4090-8d5e-e60089e1fb38.png)

**Comment by banavalikar** [comment]
![image](https://user-images.githubusercontent.com/10076518/133421351-4745932a-cbef-4623-9791-2e14932f7c2b.png)

**Comment by cornelcroi** [comment]
Hi,

Sorry about that, indeed some files were missing, I had used a wrong pattern in my .gitignore.
It should be fine now.
Let me know.

**Comment by banavalikar** [comment]
Hi Corneliu,

I will give it a try again.

**Comment by cornelcroi** [comment]
Closing this, it should work fine.

**Comment by olfa-arfani** [comment]
hello @cornelcroi, could you please help to let me know what kind of pattern was missing in the .gitignore to fix this issue?

**Comment by cornelcroi** [comment]
Actually, by default CDK generates a .gitignore and it ignores all .js files :).
So to fix this, I just removed that rule and pushed the code again.
Do you have an issue right now?
